[station_stars]
"NTS: Slow Focus" = 1
"NTS: Labyrinth" = 1
"FBI Radio" = 1
"NTS: House" = 1
"Juanito's local stream #1" = 1
"NTS: Memory Lane" = 1
"NTS 2" = 3
"NTS: Poolside" = 1
"NTS: Sheet Music" = 1
"Radio Universidad de Chile" = 1
"NTS: Field Recordings" = 1
"NTS: The Tube" = 1
"Juanito's local stream #3" = 1
"Juanito's local stream #2" = 1
"Lyl.live" = 1
"NTS: Sweat" = 1
"Juanito's local stream #4" = 1
"NTS 1" = 3
"NTS: Lowkey" = 1
"NTS: The Pit" = 1
"NTS: Expansions" = 1
"NTS: Xmas Crackers" = 1
"Radio Valentin Letelier" = 1
"NTS: Feelings" = 1
"NTS: Island Time" = 1

[file_stars]
